### PR TITLE
feat: Support more DDL statements

### PR DESCRIPTION
**Pull request by abdel**
Suggestions to include more DDL statements that are supported by the DDL API

### CODE REVIEW

**Comment by mdovhopo** [comment]
hey @abdel! Thank you for the contribution! The lint is failing, address that please, and i'll merge this, this is a good addition to the tool.

**Comment by abdel** [comment]
@mdovhopo thanks for that. I have addressed the lint errors now.

**Comment by mdovhopo** [comment]
@abdel merged. Changes will be in 1.7.0 version. There are some problems in release, I'll look into it. Thank you!

**Comment by abdel** [comment]
Unsure if related, but I realised that Views are not supported in the emulator. I can do another PR to ensure that they're part of the unsupported statements

**Comment by mdovhopo** [comment]
I think it is not related, but open pr anyway, of views are not supported, migrations can break at some point locally.

**Comment by mdovhopo** [comment]
@abdel works now, was some random rate limit from github. Feel free to open up new PR to ignore VIEW in emulator.

**Comment by abdel** [comment]
@mdovhopo Thanks! I have addressed these issues in the follow up PR https://github.com/mdovhopo/google-spanner-migrations-runner/pull/5

**Pull request merged**
